import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Inter, Playfair_Display } from "next/font/google";
import FloatingTimer from "./components/FloatingTimer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Adaptive Smart Study Planner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
        <Toaster position="top-right" />
        {children}
        <FloatingTimer />
      </body>
    </html>
  );
}